query findAlbums($search: AlbumsSearchInput!) {
  findAlbums(search: $search) {
    name
    url
    cover
  	released
    artist {
      name
      url
      avatar
      header
    }
    songs {
      name
      file
      released
      url
      feat {
        name
        url
        avatar
      }
    }
  }
}
