query getArtists($artistsSearch: ArtistSearchInput!) {
  getArtists(artistSearchInput: $artistsSearch) {
    name
    url
    avatar
    header
    albums {
      name
      url
      cover
    }
  }
}
