query findPlaylists($search: PlaylistSearch) {
  findPlaylists(search: $search) {
    title
    url
    availability
    cover
    owner {
      username
    }
    songs {
      name
      file
      released
      url
      album {
        name
        url
        released
        cover
      }
      feat {
        name
        url
      }
      artist {
        name
        avatar
        url
      }
    }
  }
}
